<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ADB_USB_Speed_Test</AssemblyName>
    <RootNamespace>AdbUsbSpeedTest</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>ADB_USB_Speed_Test.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
